### ISSUE TITLE
image hover on #all pages

### ISSUE THREAD

**Issue by anonish** [Pashe/8chanX#8]
When selecting all pages ("all" on the page list at bottom, which converts to 8ch.net/board/index.html#all), the image hover does not work for pages 2+
using firefox 35.x, arch linux, both 8chanx and 8chanx pure

**Comment by 7185** [comment]
That's because of this: https://github.com/Pashe/8chanX/blob/2-0/8chan-x.user.js#L1194
When you are scrolling the page, you are triggering a `new_post` event, which should call `onNewPostImageHover()`. However, that only works if you are in a thread.
So, the quick and dirty fix is to add:

``` javascript
  unsafeWindow.$(document).on('new_post', function (e, post) {
    onNewPostImageHover(post);
  });
```

at the end of your userscript.

## 

While we're at it, I'm more worried about that line:
https://github.com/Pashe/8chanX/blob/2-0/8chan-x.user.js#L317
We are using `hoverImage` which is not defined yet.
